### ISSUE TITLE
Needs textbox for user to enter score

### ISSUE THREAD

**Issue by r3dcrosse** [jasmineiris/cs177_Iro#11]
Could use a textbox on the gameplay page that lets the user enter a score for number of [color] balls counted. 

Also could use a submit button. How do we want to send/store the data?

**Comment by jasmineiris** [comment]
I like both those ideas. I think which ever you think would be the most effective method. If you did a submit button, you could display different numbers. The button with the correct number would score them the win. But imputing the number would be a bit more of a challenge for the child. They would have to be sure of the count. Which could be more effective in regards to a memory skill.

**Comment by r3dcrosse** [comment]
Added textbox and button for user to enter score.

**Comment by jasmineiris** [comment]
Nice!
