### ISSUE TITLE
Score checker needs to be developed

### ISSUE THREAD

**Issue by r3dcrosse** [jasmineiris/cs177_Iro#12]
So we have three options here: 

1) Let the user ONLY enter a number in int form (e.g "12", "5") and compare that to the actual number. 

2) Let the user ONLY enter a number in string form (e.g "twelve", "five") and write a function that converts the string to an int to compare it to the actual number. 

3) Do both?

**Comment by jasmineiris** [comment]
I'm thinking number in int because we're marketing to young children but if you feel that string format would make it a bit more challenging, maybe that's a better method.

**Comment by r3dcrosse** [comment]
I'm thinking we could do both? Because it would also allow the child to practice spelling numbers. I tend to have a lot of difficulty writing/spelling numbers out when I need to write cheques...

**Comment by jasmineiris** [comment]
sweet! Both sounds good to me!

**Comment by r3dcrosse** [comment]
Done!
