### ISSUE TITLE
Intro page

### ISSUE THREAD

**Issue by squeakyheatr** [jasmineiris/cs177_Iro#18]
I am still working hard on this issue, I keep looking for work arounds to make this intro page pretty. I promise when it is complete it will be amazing. Sorry for the delay all.

**Comment by squeakyheatr** [comment]
May I ask, would it be ok to make multiple pages? one would be Press P to Play, the other would say Count the yellow balls

**Comment by jasmineiris** [comment]
Of course. However you feel your work flow would be  more effective.

**Comment by squeakyheatr** [comment]
I just made it 2 pages with a 8 second delay for transition. Although I forgot I need a button UGGGG maybe i should throw a button up on both pages or just one?

**Comment by jasmineiris** [comment]
hmmm, both pages? which is the other page?

**Comment by squeakyheatr** [comment]
I have the first page says Press P to Play transition to next page Count the yellow balls (button to start game)

**Comment by squeakyheatr** [comment]
Or we can transition it with a timer to start game

**Comment by squeakyheatr** [comment]
It looks pretty is all, was about to push it haha but let me know what you think, timer or button to start the game

**Comment by jasmineiris** [comment]
I think a  transition timer might work but I'm now realizing what you meant by two pages. Is there a  reason why you can't add the instructions on a single page? Originally my assumption was that you needed two scripting pages: ie html + js.

**Comment by jasmineiris** [comment]
well.. go ahead and push it

**Comment by jasmineiris** [comment]
after the transitioning page is completed

**Comment by squeakyheatr** [comment]
I've been working on trying to find a solution but everything I have tried hasn't worked. The issue at hand is: the last call to the js file is the only one that shows up. Every time I try to line break the string it gives me weird ascii characters in place of line breaks in the string. I have tried putting single graphics on single canvases but even when I tried to put the canvas one on top of the other, all I would see is the last call. Its been a weird problem I have been trying to solve. I think the problem may lie within the JS code and not the HTML portion, I have to go over the code again to keep looking for a work around. 

But lastly, how would you like the transition to the game to be? through button or timer? (before I push it)

**Comment by jasmineiris** [comment]
Timer and can you screen shot you bug to later. e-mail it to me. thanks. It sounds like it might be your source path.

**Comment by squeakyheatr** [comment]
I can show you the bug later. But which one, the one where only the last call is shown, or the ascii symbols when I try a line break?

**Comment by jasmineiris** [comment]
Both but like you said when I see you next. I might be able to fix the issue with the push you make now. I can try to combine the pages for now just push what you have so I can run it.

**Comment by squeakyheatr** [comment]
I have pushed it now

**Comment by jasmineiris** [comment]
I'm in sql, once I'm home I'll check it out. It will be an hour.

**Comment by squeakyheatr** [comment]
all good just glad I was able to work towards something, hope it can make the game haha

**Comment by jasmineiris** [comment]
resolved: made some changes; updated test, colors, links, and transition
