### ISSUE TITLE
Functional spec needs to be written...

### ISSUE THREAD

**Issue by r3dcrosse** [jasmineiris/cs177_Iro#20]

**Comment by iandroni** [comment]
I will work on it as soon as we have competed the game

**Comment by r3dcrosse** [comment]
Game is technically completed at this point.

**Comment by iandroni** [comment]
I'll start updating the specs and documentation in general then

**Comment by jasmineiris** [comment]
updated music and changed fading effect for timing of the game. Play again before writing up specs.

**Comment by iandroni** [comment]
All done

**Comment by evmo** [comment]
re-written & edited for report
