### ISSUE TITLE
Music doesn't work

### ISSUE THREAD

**Issue by r3dcrosse** [jasmineiris/cs177_Iro#22]
Do we want background music for the game? If so, we need to fix it so it works. I think it doesn't work currently because there's no music file anymore... 

If we don't want background music in the game, then we need to remove the audio control buttons.

**Comment by iandroni** [comment]
I thought  we already had background music set up, what happened to it?

**Comment by r3dcrosse** [comment]
It looks like it's missing the music file on this repo. The file was called 'Simon_Says.mp3'.

**Comment by jasmineiris** [comment]
I'll check it

**Comment by jasmineiris** [comment]
There's nothing wrong with the MUSIC. I'm closing this issue out

**Comment by r3dcrosse** [comment]
No wait, look at what's on your repo... I can't find the music file anywhere there and it doesn't play when I run the game.

**Comment by jasmineiris** [comment]
let me check it out

**Comment by jasmineiris** [comment]
Hey David, it looks like from the history you accidentally deleted the file in change list: 53da318

**Comment by jasmineiris** [comment]
I believe I have a copy on my computer. I'll fix it

**Comment by r3dcrosse** [comment]
@jasmineiris Ahhhh, my bad. I don't have the file anymore. Would you mind fixing it? Sorry about that.

**Comment by jasmineiris** [comment]
Music is working!!!! @r3dcrosse great job on the score tracker!
