### ISSUE TITLE
Instruction page

### ISSUE THREAD

**Issue by iandroni** [jasmineiris/cs177_Iro#23]
We have 2 types of instruction  pages in our game, I think we should leave the interactive one (java script), we should have one after we enter the game and the same one after we push "play again" button( we have 2 different )

**Comment by r3dcrosse** [comment]
What/where are the two types of instruction pages called/located?

**Comment by iandroni** [comment]
Wait, let me check

**Comment by iandroni** [comment]
Never mind, I had an old html  page messed up with new JS. Ignore the issue
