### ISSUE TITLE
User testing issue

### ISSUE THREAD

**Issue by iandroni** [jasmineiris/cs177_Iro#24]
After player counted the yellow bowls, she/he needs to enter the amount , then message pops out about the result. Can we add a message like "Enter the number, please!" if they enter anything else but the number ? At this point if user enters letter , empty result block pops out with 2 buttons .

**Comment by r3dcrosse** [comment]
We currently have it set up so if the user spells out the actual number of balls (e.g. "twelve") then it checks that too. This can encourage the user to learn how to spell numbers, therefore if the number isn't spelled correctly, then they need to try again.

**Comment by iandroni** [comment]
Good to know, that is definitely should be in user documentation.
