### ISSUE TITLE
User Tester Feedback from Brick

### ISSUE THREAD

**Issue by jasmineiris** [jasmineiris/cs177_Iro#39]
A.Bricks Suggestions:

Default too many circles 
Create levels: 
Randomization per circle for each level
Graphic style should be the same: making the font and frame look similar goes a long way
Fading effect timing should slowdown if more circles appear
Gravity cluster incorporate better into the game or added more dimension to the circles using the gravity effect

**Comment by evmo** [comment]
adding this to the readme
